#!/bin/bash -eu

#local paths
export OPENSHIFT_HASKELL_DIR=`pwd`
export PATH=`pwd`/usr/ghc/bin:$PATH

#initialise the global package db
ghc-pkg recache

#prepare cabal
openshift=`pwd`/.openshift
sed -i "s|!openshift!|$openshift|g" $openshift/config
sed -i "s|!OPENSHIFT_HASKELL_DIR!|$OPENSHIFT_HASKELL_DIR|g" $openshift/config
sed -i "s|!packages!|$OPENSHIFT_DATA_DIR/packages|g" $openshift/config
export CABAL_CONFIG=$openshift/config
cabal update

#install packages
case $build in
  network)
    cabal install --global network
    ;;
  mflow)
    cabal install --global MFlow
    ;;
  yesod)
    cabal install --global yesod-platform happy esqueleto
    ;;
  snap)
    cabal install --global snap
    ;;
  scotty)
    cabal install --global scotty
    ;;
  happstack)
    cabal install --global happy
    cabal install --global hsx2hs
    cabal install --global happstack-foundation
    ;;
  *)
    echo Unknown build option $build
    exit 1
esac

#convert absolute paths in package db to relative
usr=`pwd`/usr
ghc=$usr/ghc/lib
packages=$ghc/ghc-7.6.3/package.conf.d
sed -i "s|$ghc|\$topdir/..|g" $packages/*.conf
sed -i "s|$usr|\$topdir/../../..|g" $packages/*.conf
rm $packages/package.cache

#remove references to non-existent documentation
sed -i "s|haddock-interfaces: .*|haddock-interfaces:|g" $packages/*.conf
sed -i "s|haddock-html: .*|haddock-html|g" $packages/*.conf

#package the cartridge
mv .openshift/manifests/$build.yml metadata/manifest.yml
zip -r .openshift/$build.zip *
