#!/bin/bash -eu

if [ $dev = "true" ]; then
  build=dev
  #unlock all files
  sed -i '/processed_templates/,$!d' metadata/managed_files.yml
fi
echo "Source-Url: http://www.accursoft.com/cartridges/$build.zip" >>metadata/manifest.yml
zip -r .openshift/$build.zip *
mv metadata/manifest.yml .openshift/$build.yml
